### ISSUE TITLE
[NSAlert runAsPopoverForView:withCompletionBlock:] unrecognized selector sent to instance

### ISSUE THREAD

**Issue by w-i-n-s** [raffael/NSAlert-Popover#2]
Hi. I just want to try your code. I create default project, add button to window and add action
# import "AppDelegate.h"
# import "NSAlert+Popover.h"

@implementation AppDelegate
- (IBAction)showBubble:(id)sender {
  
  NSAlert *alert = [NSAlert alertWithMessageText:@"Do you really want to delete this item?"
                                   defaultButton:@"Delete"
                                 alternateButton:@"Learn more"
                                     otherButton:@"Cancel"
                       informativeTextWithFormat:@"Deleting this item will erase all associated data in the database. Click learn more if you need additional information."];
  
  [alert runAsPopoverForView:_window.contentView
         withCompletionBlock:^(NSInteger *result) {
      // handle result
  }];  
  }
  @end

what I do wrong? Can you give the demo project?

**Comment by raffael** [comment]
You need to provide the button itself (which inherits from NSView and thus is a NSView) as the view for which you want to pop up the alert.
- (IBAction)showBubble:(NSView *) button {

NSAlert *alert = [NSAlert alertWithMessageText:@"Do you really want to delete this item?"
defaultButton:@"Delete"
alternateButton:@"Learn more"
otherButton:@"Cancel"
informativeTextWithFormat:@"Deleting this item will erase all associated data in the database. Click learn more if you need additional information."];

[alert runAsPopoverForView:button
withCompletionBlock:^(NSInteger *result) {
// handle result
}];

Does it work for you?

**Comment by w-i-n-s** [comment]
nope. here is the project
https://dl.dropboxusercontent.com/u/30736398/123.zip

**Comment by raffael** [comment]
That was a hard one!
Two things caused the error:

(1) You did not include the category files (NSAlert...h, NSAlert...m) in the Build Phase, that is, Xcode is suggesting that the method runAsPopoverForView:withCompletionBlock:; exists, but the actual compiled app does not have the category included, and thus, will spawn the error. Make sure to have listed the category in your Target settings within the Build Phase ("Compile Sources").

(2) You do not have activated Automatic Reference Counting in your project. This NSAlert category has not been tested in non-ARC projects. Currently it's ARC compatible only! Sorry, I should have mentioned that, will add it to the docs!

**Comment by w-i-n-s** [comment]
Yes, non-ARC
